-- movimentacao_financeira
SELECT 
	eg.uf ,
	eg.coes ,
	eg.rota ,
	eg.carga ,
	eg.cidade ,
	eg.unidade ,
	eg.vendedor ,
	eg.acrescimo ,
	eg.date_part ,
	eg.cod_pedido ,
	eg.cod_cliente ,
	eg.preco_medio ,
	eg.cod_romaneio ,
	eg.nome_cliente,
	eg.nome_produto ,
	eg.qtd_entregue ,
	eg.tipo_entrega ,
	eg.tipo_produto ,
	eg.tipo_unidade ,
	eg.tipo_veiculo ,
	eg.peso_entregue ,
	eg.placa_veiculo ,
	eg.classe_produto ,
	eg.custo_entregue ,
	eg.valor_entregue ,
	eg.data_hora_pedido ,
	eg.categoria_produto ,
	eg.metragem_entregue ,
	eg.data_hora_entregue ,
	eg.sub_classe_produto ,
	eg.custo_unitario_produto 
FROM  
    entregas_geral eg 
WHERE 
  eg.data_hora_entregue BETWEEN '2024-06-01' AND '2024-06-30'
ORDER BY 
  	eg.uf ,
	eg.coes ,
	eg.rota ,
	eg.carga ,
	eg.cidade ,
	eg.unidade ,
	eg.vendedor ,
	eg.acrescimo ,
	eg.date_part ,
	eg.cod_pedido ,
	eg.cod_cliente ,
	eg.preco_medio ,
	eg.cod_romaneio ,
	eg.nome_cliente,
	eg.nome_produto ,
	eg.qtd_entregue ,
	eg.tipo_entrega ,
	eg.tipo_produto ,
	eg.tipo_unidade ,
	eg.tipo_veiculo ,
	eg.peso_entregue ,
	eg.placa_veiculo ,
	eg.classe_produto ,
	eg.custo_entregue ,
	eg.valor_entregue ,
	eg.data_hora_pedido ,
	eg.categoria_produto ,
	eg.metragem_entregue ,
	data_hora_entregue ,
	eg.sub_classe_produto ,
	eg.custo_unitario_produto  