-- pedidos mês
SELECT 
	p.id ,
	p.coes ,
	p.id_item ,
	p.vendedor ,
	p.cod_pedido ,
	p.cod_cliente ,
	p.cod_produto ,
	DATE(p.data_pedido ::timestamp) as data_pedido ,
    p.pedido_pago ,
    p.pedido_cliente ,
    p.qtd_produto ,
    p.tipo_pedido ,
    p.endereco_gps ,
    p.last_updated ,
    p.nome_cliente ,
    p.nome_produto ,
    p.rota_entrega ,
    p.tipo_produto ,
    p.tipo_unidade ,
    p.medida_altura ,
    p.metragem_real ,
    p.pedido_pronto ,
    p.status_pedido ,
    MAX(p.classe_produto) AS classe_produto ,
    p.cond_pagamento ,
    p.medida_largura ,
    p.pedido_cliente ,
    p.valor_desconto ,
    p.valor_acrescimo ,
    p.data_hora_pedido ,
    p.metragem_cobrada ,
    p.previsao_entrega ,
    p.categoria_produto ,
    MAX(p.sub_classe_produto) AS sub_classe_produto ,
    p.valor_final_pedido ,
    p.valor_total_pedido ,
    p.percentual_desconto ,
    p.percentual_acrescimo ,
    p.valor_unitario_total ,
    p.valor_unitario_produto ,
    p.custo_unitario_total_produto ,
    p.valor_unitario_com_desconto ,
    p.custo_unitario_produto ,
    p.valor_unitario_total_com_desconto 
FROM 
    pedidos p
where 
	p.unidade = '3D Vidros'
	and cod_pedido = '52293'
group by
	p.id ,
	p.coes ,
	p.id_item ,
	p.vendedor ,
	p.cod_pedido ,
	p.cod_cliente ,
	p.cod_produto ,
	data_pedido ,
    p.pedido_pago ,
    p.qtd_produto ,
    p.tipo_pedido ,
    p.endereco_gps ,
    p.last_updated ,
    p.nome_cliente ,
    p.nome_produto ,
    p.rota_entrega ,
    p.tipo_produto ,
    p.tipo_unidade ,
    p.medida_altura ,
    p.metragem_real ,
    p.pedido_pronto ,
    p.status_pedido ,
	classe_produto ,
    p.cond_pagamento ,
    p.medida_largura ,
    p.pedido_cliente ,
    p.valor_desconto ,
    p.valor_acrescimo ,
    p.data_hora_pedido ,
    p.metragem_cobrada ,
    p.previsao_entrega ,
    p.categoria_produto ,
   	sub_classe_produto ,
    p.valor_final_pedido ,
    p.valor_total_pedido ,
    p.percentual_desconto ,
    p.percentual_acrescimo ,
    p.valor_unitario_total ,
    p.valor_unitario_produto ,
    p.custo_unitario_total_produto ,
    p.valor_unitario_com_desconto ,
    p.custo_unitario_produto ,
    p.valor_unitario_total_com_desconto 