    select * from entregas_geral
    where unidade in (
    'Oazem','INBRAVIDROS', '4D Vidros', 'BRASILIA', 'FORTALEZA', 'VITORIA DE SANTO ANTAO',
    'ALLGLASS TEMPERA','TEMPER PATOS','Alumiaco Recife','GM Recife','Agreste Vidros',
    'GM Salvador', 'GM Maceio', 'IDVIDROS', 'PERFILUX', 'OLINDA','IRECE', 'ARAPIRACA',
    'BARROSREIS','GMFEIRA','GM JUAZEIRO', 'SOBRAL','GM FORTALEZA','DVM PARAIBA','BELGA POLIMEROS',
    'ALLGLASS LOJA', 'GM FORTALEZA FILIAL', 'GM MONTESE', 'CD VIDROS', 'CD ALUMINIO','PONTO VIDRO',
    'BFVIDROS','CAMACARI','PICOS','RPVDIROS','CAPIMGROSSO', 'RNVIDROS', 'GRAVATA', 'BELO JARDIM',
    'ALAGOINHA','ARCOVERDE','IGARASSU','SALGUEIRO', 'MANDACARU','ARENAVIDROS', 'CRUZ DAS ALMAS',
    'ITAPIPOCA', 'DELMIRO GOUVEIA','SANTA CRUZ','GOIANA','ALAGOAS VIDROS', 'CABO VIDROS')